nouns = nouns.concat([
    'man',
    'bear',
    'pig',
    'computer',
    'tree',
    'mess',
    'sewage',
    'dream',
    'chocolate',
    'baby',
    'the dean',
    'university',
    'refrigerator',
    'MBA student',
    'SOM faculty',
    'bald chicken',
    'bubble tea',
    'latte'
]);
