adjectives = adjectives.concat([
    'short',
    'crafty',
    'wiley',
    'sophisticated',
    'hedonistic',
    'lazy',
    'narcissistic',
    'demure',
    'ancient',
    'pungent',
    'smoggy',
    'barbaric',
    'drab',
    'sweaty',
    'majestic',
    'ugly',
    'foul',
    'agile',
    'bricks-and-clicks',
    'cloudified',
    'omnichannel',
    'cost effective',
    'hot',
    'backend',
    'cross functional',
    'elastic',
    'leading-edge',
    'resource sucking'
]);
