adjectives = adjectives.concat([
    'short',
    'crafty',
    'wiley',
    'sophisticated',
    'hedonistic',
    'lazy',
    'narcissistic',
    'demure',
    'ancient',
    'pungent',
    'smoggy',
    'barbaric',
    'drab',
    'sweaty',
    'majestic',
    'ugly',
    'foul'
]);
